config/routes.rb
Rails.application.routes.draw do

  

  devise_for :users

  root 'amsgroups#welcome'
  
  scope "/:locale", locale: /en|ru|ar/ do
    
        end
      resources :amsgroups
      resources :amsgrouppictures
      resources :amsfoods
      resources :amsfoodpictures
      resources :amsstones
      resources :amsstonepictures

      resources :categories
      resources :foodcategories
      resources :stonecategories
      resources :groupcategories

  

end

app/models/amsfood.rb
class Amsfood < ActiveRecord::Base
  belongs_to :user
  belongs_to :foodcategory

  has_attached_file :imagefood, styles: { small: "116x116#" , medium: "252x302#", simple: "350x350#" , thumb: "150x150#", hard: "1152x1000#" }, default_url: "/images/:style/points.png"
  validates_attachment_content_type :imagefood, content_type: /\Aimage\/.*\z/	

  translates :titlerus, :descriptionrus
end

app/models/amsfoodpicture.rb
class Amsfoodpicture < ActiveRecord::Base

  belongs_to :user


  has_attached_file :imagefoodpicture, styles: { medium: "631x185#", thumb: "382x300#" }, default_url: "/images/:style/points.png"
  validates_attachment_content_type :imagefoodpicture, content_type: /\Aimage\/.*\z/

  translates :titlerus, :descriptionrus
end

app/models/amsgroup.rb
class Amsgroup < ActiveRecord::Base

  belongs_to :user
  belongs_to :groupcategory


	  has_attached_file :imagegroup, styles: { medium: "302x252#", thumb: "100x100#" }, default_url: "/images/:style/points.png"
  validates_attachment_content_type :imagegroup, content_type: /\Aimage\/.*\z/

  translates :titlerus, :descriptionrus
end

app/models/amsgrouppicture.rb
class Amsgrouppicture < ActiveRecord::Base


  belongs_to :user


  has_attached_file :imagegrouppicture, styles: { medium: "920x150#", thumb: "100x100#" }, default_url: "/images/:style/points.png"
  validates_attachment_content_type :imagegrouppicture, content_type: /\Aimage\/.*\z/

  translates :titlerus, :descriptionrus
end

app/models/amsstone.rb
class Amsstone < ActiveRecord::Base

  belongs_to :user
  belongs_to :stonecategory


  has_attached_file :imagestone, styles: { small: "116x116#" , medium: "252x302#", simple: "350x350#" , thumb: "150x150#", hard: "1152x1000#" }, default_url: "/images/:style/points.png"
  validates_attachment_content_type :imagestone, content_type: /\Aimage\/.*\z/

  translates :titlerus, :descriptionrus
end

app/models/amsstonepicture.rb
class Amsstonepicture < ActiveRecord::Base
	
  belongs_to :user


  has_attached_file :imagestonepicture, styles: { medium: "631x185#", thumb: "382x300#" }, default_url: "/images/points.png"
  validates_attachment_content_type :imagestonepicture, content_type: /\Aimage\/.*\z/


  translates :titlerus, :descriptionrus
end

app/models/category.rb
class Category < ActiveRecord::Base
	belongs_to :user

	#has_many :amsfoods
	#has_many :amsstones
	#has_many :amsgroups
end

app/models/foodcategory.rb
class Foodcategory < ActiveRecord::Base
		belongs_to :user

	has_many :amsfoods


	translates :categoryname
end

app/models/groupcategory.rb
class Groupcategory < ActiveRecord::Base
		belongs_to :user


	has_many :amsgroups

	translates :categoryname
end

app/models/stonecategory.rb
class Stonecategory < ActiveRecord::Base
		belongs_to :user


	has_many :amsstones

	translates :categoryname
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :amsfoods
  has_many :amsfoodpictures
  has_many :amsgroups
  has_many :amsgrouppictures
  has_many :amsstones
  has_many :amsstonepictures
  has_many :categories
  has_many :foodcategories
  has_many :groupcategories
  has_many :stonecategories
end

app/controllers/amsfoods_controller.rb
class AmsfoodsController < ApplicationController
	before_action :find_amsfood, only: [ :show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]


	def index
		#@amsgroup = Amsgroup.all.order("created_at DESC")
			@amsgrouppicture = Amsgrouppicture.all.order("created_at DESC")
		#@amsstone = Amsstone.all.order("created_at DESC")
			@amsstonepicture = Amsstonepicture.all.order("created_at DESC")
		#@amsfood = Amsfood.all.order("created_at DESC")
			@amsfoodpicture = Amsfoodpicture.all.order("created_at DESC")
		#@category = Category.all.order("created_at DESC")

			@amsgroup = Amsgroup.all.order("created_at DESC")


		#if params[:category].blank?
		#	@amsgroup = Amsgroup.all.order("created_at DESC")
		#	@amsstone = Amsstone.all.order("created_at DESC")
		#	@amsfood = Amsfood.all.order("created_at DESC")
		#	@category = Category.all.order("created_at DESC")
		#else
		#	@category_id = Category.find_by(categoryname: params[:category]).id
		#	@amsgroup = Amsgroup.where(category_id: @category_id).order("created_at DESC")
		#	@amsstone = Amsstone.where(category_id: @category_id).order("created_at DESC")
		#	@amsfood = Amsfood.where(category_id: @category_id).order("created_at DESC")
		#end

		if params[:foodcategory].blank?
			@amsfood = Amsfood.all.order("created_at DESC")
		else
			#@stonecategory_id = Stonecategory.find_by(categoryname: params[:stonecategory]).id
			@amsfood = Amsfood.where(foodcategory_id: @foodcategory_id).order("created_at DESC")

			#@resumes = Resume.where(soul_id: @soul).order("created_at DESC")
		end

		
	end

	def show
		@amsfoody =  @amsfood.foodcategory_id
		@foodcategory = Foodcategory.where(foodcategory_id: @amsfoody).order("created_at DESC")
	end

	def new
		@amsfood = current_user.amsfoods.build
	end

	def create
		@amsfood = current_user.amsfoods.build(amsfood_params)

		if @amsfood.save
			redirect_to @amsfood, notice: "wish was succesfully updated!"
		else
			render 'new'
		end
	end

	def edit
		
	end

	def update
		if @amsfood.update(amsfood_params)
			redirect_to @amsfood
		else
			render "edit"
		end
	end

	def destroy
		@amsfood.destroy
		redirect_to @amsfood
	end

	private

	def amsfood_params
		params.require(:amsfood).permit(:titlerus, :descriptionrus, :foodcategory_id, :imagefood, :amsfoods_id)
	end

	def find_amsfood
		@amsfood = Amsfood.find(params[:id])
	end

end

app/helpers/amsfoodpictures_helper.rb
module AmsfoodpicturesHelper
end

app/helpers/amsfoods_helper.rb
module AmsfoodsHelper
end

app/helpers/amsgrouppictures_helper.rb
module AmsgrouppicturesHelper
end

app/helpers/amsgroups_helper.rb
module AmsgroupsHelper
end

app/helpers/amsstonepictures_helper.rb
module AmsstonepicturesHelper
end

app/helpers/amsstones_helper.rb
module AmsstonesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/foodcategories_helper.rb
module FoodcategoriesHelper
end

app/helpers/groupcategories_helper.rb
module GroupcategoriesHelper
end

app/helpers/stonecategories_helper.rb
module StonecategoriesHelper
end

app/views/amsfoods/_food_form.html.haml
.currentResumeEditForm
  .col-xs-1.col-md-1
    .btn_back
    = link_to "Back", root_path, class: "btn btn-default"
  .col-xs-10.col-md-10
    .tit_desc_img_block
      = simple_form_for @amsfood, html: { multipart: true } do |f|
        - if @amsfood.errors.any?
          #errors
            %p
              = @amsfood.errors.count
              Prevented this amsstone froms saving
            %ul
              - @amsfood.errors.full_messages.each do |msg|
                %li= msg
        .panel-body
          = f.collection_select :foodcategory_id, Foodcategory.all, :id, :categoryname, {promt: "Выберите Категорию"}, class: 'form-control'

          = f.input :titlerus, label: 'ИМЯ НОВОЙ ЕДИНИЦЫ ТОВАРА', input_html: { title: "ИМЯ НОВОЙ ЕДИНИЦЫ ТОВАРА", class: 'form-control'}
          
          = f.input :descriptionrus, label: 'ОПИСАНИЕ НОВОЙ ЕДИНИЦЫ ТОВАРА', input_html: { title: "ОПИСАНИЕ НОВОЙ ЕДИНИЦЫ ТОВАРА", class: 'form-control'}
          
          = f.input :imagefood, label: 'Выберите изображение', input_html: { class: 'form-control'}

        .sub_button
          = f.button :submit, class: "btn btn-primary sub_button"
        .btn_bottom_back
          = link_to "Back", root_path, class: "btn btn-default btn_bottom_back"
  .col-xs-1.col-md-1

app/views/amsfoods/edit.html.haml
%h1 Edit @amsfood.title

= render "food_form"

%br

app/views/amsfoods/index.html.haml
%div.bodyams
  .bodyhead
    %div.amslogo
      = link_to image_tag( 'logo-ams.svg', :class => 'ams_logo_head' ), amsgroups_path, target: '_blank'
      %div.amslogolanguage
        %h3
          = link_to_unless_current "English",  amsgroups_path(locale: "en")
          \#{link_to_unless_current "Arabic",  amsgroups_path(locale: "ar")} |
          \#{link_to_unless_current "Rusian",  amsgroups_path(locale: "ru")}
    %div.tabbed
      %input{:type=>"radio", :name => "tabs", :id=>"tab-nav-1", :checked=> true}
        %label{:for=>"tab-nav-1"}=t 'welcome.ams'
      %input{:type=>"radio", :name => "tabs", :id=>"tab-nav-2"}
        %label{:for=>"tab-nav-2"}=t 'welcome.howwework'
      %input{:type=>"radio", :name => "tabs", :id=>"tab-nav-3"}
        %label{:for=>"tab-nav-3"}=t 'welcome.production'
      %input{:type=>"radio", :name => "tabs", :id=>"tab-nav-4"}
        %label{:for=>"tab-nav-4"}=t 'welcome.contacts'
      .bodyamsgroup
      %div{ :class => ['tabs']}

          
        %div.amsgroupproduction
          = render 'layouts/navigation'
          %div.stprod.amsproductsstones.foodcolor 
            %h2=t 'welcome.foodproduction' 
            .div.textcenter
              - Foodcategory.all.each do |food|
                /= cat.categoryname
                %h3.inline

                  = link_to food.categoryname , food
            .categoryblokstonefood
              - @amsfood.each do |f|
                .allproductplate.inline
                  %h4= link_to truncate(f.titlerus, length: 20), f
                  .allproductplateimg
                    = link_to f do
                      = image_tag f.imagefood.url(:thumb)  
                  - if user_signed_in?
                    %h5.stoneplatetext= link_to truncate(f.descriptionrus, length: 20), f
                  - else
                    %h5.stoneplatetext #{truncate(f.descriptionrus, length: 20)}
            .div
        /
          %div.stone_gallery
            - @amsgroup.each_slice(3) do |group|
              %div
                - group.each do  |s|
                  .ams_gallery_foto
                    = link_to s do
                      = image_tag s.imagegroup.url(:medium)
                  %h2= link_to s.titlerus, s
        %div
          %div.amsworktext

            %div.amsworknews.right
              %h1{:style => "color: #ffd700; text-align: center"} OUR NEWS
              - @amsgroup.each do |group|
                %h2
                  - if user_signed_in?
                    = link_to group.titlerus, group
                  - else
                    = group.titlerus
                  .newstime.right
                    %h5
                      = group.updated_at.day
                      ∕
                      = group.updated_at.month
                      ∕
                      = group.updated_at.year
                %h4{:style => "color: #ffd700;"}= group.descriptionrus
                %hr{:style => "border: 2px double #50156E; margin-top: 10px;"}
            %h1{:style => "color: #ffd700; text-align: center; margin-top: 0px;"}=t 'welcome.howweworktitle'
            %p=t 'welcome.howweworktext' 
          %div.amsgroupfoodandstone
            %div.amsgroupfoodandstoneplate.inline
              %div.amsgroupfshead.amsgroupfsheadgrey= link_to "AMS Stones", amsstones_path, class: " btn asmstone_button"
              %div.amsgroupfsbody
                %div.slides_fs
                  %ul
                    %li
                      = link_to image_tag( 'stone1', :class => 'amsgroupfoodfoto' ), amsstones_path
                    %li
                      = link_to image_tag( 'stone2', :class => 'amsgroupfoodfoto' ), amsstones_path
                    %li
                      = link_to image_tag( 'stone3', :class => 'amsgroupfoodfoto' ), amsstones_path
                    %li
                      = link_to image_tag( 'stone4', :class => 'amsgroupfoodfoto' ), amsstones_path
            %div.amsgroupfoodandstoneplate.inline
              %div.amsgroupfshead.amsgroupfsheadred= link_to "AMS Foods", amsfoods_path, class: " btn asmfood_button"
              %div.amsgroupfsbody
                %div.slides_fs
                  %ul
                    %li
                      = link_to image_tag( 'food1', :class => 'amsgroupfoodfoto' ), amsfoods_path
                    %li
                      = link_to image_tag( 'food2', :class => 'amsgroupfoodfoto' ), amsfoods_path
                    %li
                      = link_to image_tag( 'food3', :class => 'amsgroupfoodfoto' ), amsfoods_path
                    %li
                      = link_to image_tag( 'food4', :class => 'amsgroupfoodfoto' ), amsfoods_path
        %div 
          %div.amsworktext
            = render 'layouts/navigation'
        %div
          %div.amsmap.right
            %iframe{:allowfullscreen => "", :frameborder => "0", :height => "350", :src => "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2539.730208596946!2d30.431012037035497!3d50.46474843315227!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xdc777aaaf995bf05!2z0KTQu9C-0YDQsCDQn9Cw0YDQug!5e0!3m2!1sru!2sua!4v1479894063059", :style => "border:0", :width => "450"}
          
          .ams_contacts
            %h2=t 'welcome.contacts'
            %li.inline
              = link_to image_tag( 'mail.svg', :class => 'mail' ), amsgroups_path, target: '_blank'
              %div.number international.ams.group@gmail.com
            %li
              = link_to image_tag( 'skype.svg', :class => 'wel_contact' ), amsgroups_path, target: '_blank'
              = link_to image_tag( 'facebook-square.svg', :class => 'wel_contact' ), amsgroups_path, target: '_blank'
              
            %li
              = link_to image_tag( 'viber.svg', :class => 'wel_contact inline' ), amsgroups_path, target: '_blank'
              = link_to image_tag( 'whatsapp.svg', :class => 'wel_contact inline' ), amsgroups_path, target: '_blank'
              %div.number +380934637692     
            %li
              %h3=t 'welcome.adress'

app/views/amsfoods/new.html.haml
%h1 НОВЫЙ ПИЩЕВОЙ ТОВАР

= render "food_form"

%br
= link_to "Back", root_path, class: "btn btn-default btn_bottom_back"

app/views/amsfoods/show.html.haml
= render 'layouts/miniheader'
.headcurrentstone
  .div.headcurrentstoneams
    %h1.textcenter=t 'welcome.foodproduction'
  .div.headcurrentstoneblocks.inline
    .div.headcurrentstonefirstblock.inline.left
      %h1= link_to truncate(@amsfood.foodcategory.categoryname, length: 15), foodcategory_path(@amsfoody)
      .div= image_tag @amsfood.imagefood.url(:simple), class: "headcurrentstonepicture"
    .div.headcurrentstonesecondblock.inline.left
      %h1
        = @amsfood.titlerus
      %h2
        /= @amsfood.number
      %br
      %h3.textleft= @amsfood.descriptionrus
      %br


      - if user_signed_in?
        = link_to "Edit", edit_amsfood_path, class: "btn btn-default"
        = link_to "delete", amsfood_path, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default"
    .div.headcurrentstonethirdblock.inline
      %h1= link_to "All Foods", amsfoods_path
.bodycurrentstone
  = image_tag @amsfood.imagefood.url(:hard, class: "ams_gallery_foto")



/%h1 this is the face of user, like a person status
/= image_tag @amsfood.imagefood.url(:medium, class: "ams_gallery_foto")
/%h2= @amsfood.titlerus
/%br
/%h3= @amsfood.descriptionrus
/%br

/= link_to "Back", amsfoods_path, class: "btn btn-default"
/- if user_signed_in?
/  = link_to "Edit", edit_amsfood_path, class: "btn btn-default"
/  = link_to "delete", amsfood_path, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default"

app/views/amsfoods/welcome.html.haml
%div.foodheadmain
  %div.formargin
    %div.foodhead
      %div.foodlanguage.inline
        %ul
          %li.language EN
          %li.language AR
          %li.language RU 
      %div.foodlogo.inline
        .bootstile
          .col-xs-5.col-md-5
            %div.center.inline
              = link_to image_tag( 'AMS1.png', :class => 'ams_logo_head' ), amsgroups_path, target: '_blank'
          .col-xs-7.col-md-7
            %div.slides.inline
              %ul
                %li
                  =image_tag( '1.jpg', :class => 'foto_slider_group' )
                  %div 
                    %p МУКА
                %li
                  =image_tag( '2.jpg', :class => 'foto_slider_group' )
                  %div 
                    %p КАЧЕСТВО
                %li
                  =image_tag( '8.jpg', :class => 'foto_slider_group' )
                  %div 
                    %p ПОДСОЛНЕЧНОЕ МАСЛО
                %li
                  =image_tag( '4.jpg', :class => 'foto_slider_group' )
                  %div 
                    %p ПЕЛЬМЕНИ
                %li
                  =image_tag( '6.jpg', :class => 'foto_slider_group' )
                  %div 
                    %p ДОВЕРИЕ
                %li
                  =image_tag( '1.jpg', :class => 'foto_slider_group' )
                  %div 
                    %p ЗЕРНО
      
      %div.groupcontact.inline
        %li.contact 
          = link_to image_tag( 'google-plus-3-512.png', :class => 'contacts_to_group' ), amsgroups_path, target: '_blank'
        %li.contact
          = link_to image_tag( 'facebook-3-512.png', :class => 'contacts_to_group' ), amsgroups_path, target: '_blank'
        %li.contact
          = link_to image_tag( 'skype-3-512.png', :class => 'contacts_to_group' ), amsgroups_path, target: '_blank'

.tabbedf
  %input{:type=>"radio", :name => "tabsf", :id=>"ftab-nav-1", :checked=> true}
    %label{:for=>"ftab-nav-1"} AMS Foods 
  %input{:type=>"radio", :name => "tabsf", :id=>"ftab-nav-2"}
    %label{:for=>"ftab-nav-2"} AMS Foods who we are
  %input{:type=>"radio", :name => "tabsf", :id=>"ftab-nav-3"}
    %label{:for=>"ftab-nav-3"} Production 
  %input{:type=>"radio", :name => "tabsf", :id=>"ftab-nav-4"}
    %label{:for=>"ftab-nav-4"} Contacts
  %div{ :class => ['tabsf']}
    %div
      %h2 главная
      %p Компания <strong>AMS Internatioanl</strong> предоставляет услуги доставки\заказа материала и изделий из гранита, а так же предоставляет отдельные услуги грузодоставки подобных материалов между объектами, по Украине и странам Евросоюза. Более детальную информацию о материалах, их цене и контакты Вы можете найти в соответствующих разделах сайта.
      .navbar-brand= link_to "AMS Group", amsgroups_path
    %div
      %h2 главная
      %p Компания <strong>AMS Internatioanl</strong> предоставляет услуги доставки\заказа материала и изделий из гранита, а так же предоставляет отдельные услуги грузодоставки подобных материалов между объектами, по Украине и странам Евросоюза. Более детальную информацию о материалах, их цене и контакты Вы можете найти в соответствующих разделах сайта.
    %div
      %h2 главная
      %p Компания <strong>AMS Internatioanl</strong> предоставляет услуги доставки\заказа материала и изделий из гранита, а так же предоставляет отдельные услуги грузодоставки подобных материалов между объектами, по Украине и странам Евросоюза. Более детальную информацию о материалах, их цене и контакты Вы можете найти в соответствующих разделах сайта.
    %div
      %h2 главная
      %p Компания <strong>AMS Internatioanl</strong> предоставляет услуги доставки\заказа материала и изделий из гранита, а так же предоставляет отдельные услуги грузодоставки подобных материалов между объектами, по Украине и странам Евросоюза. Более детальную информацию о материалах, их цене и контакты Вы можете найти в соответствующих разделах сайта.