config/routes.rb
Rails.application.routes.draw do

  

  devise_for :users

  root 'amsgroups#welcome'
  
  scope "/:locale", locale: /en|ru|ar/ do
    
        end
      resources :amsgroups
      resources :amsgrouppictures
      resources :amsfoods
      resources :amsfoodpictures
      resources :amsstones
      resources :amsstonepictures

      resources :categories
      resources :foodcategories
      resources :stonecategories
      resources :groupcategories

  

end

app/models/amsstone.rb
class Amsstone < ActiveRecord::Base

  belongs_to :user
  belongs_to :stonecategory


  has_attached_file :imagestone, styles: { small: "116x116#" , medium: "252x302#", simple: "350x350#" , thumb: "150x150#", hard: "1152x1000#" }, default_url: "/images/:style/points.png"
  validates_attachment_content_type :imagestone, content_type: /\Aimage\/.*\z/

  translates :titlerus, :descriptionrus
end

app/controllers/amsstones_controller.rb
class AmsstonesController < ApplicationController
	before_action :find_amsstone, only: [ :show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		#@amsgroup = Amsgroup.all.order("created_at DESC")
			#@amsgrouppicture = Amsgrouppicture.all.order("created_at DESC")
		#@amsstone = Amsstone.all.order("created_at DESC")
			@amsstonepicture = Amsstonepicture.all.order("created_at DESC")
		#@amsfood = Amsfood.all.order("created_at DESC")
			#@amsfoodpicture = Amsfoodpicture.all.order("created_at DESC")
		#@category = Category.all.order("created_at DESC")
		    #@stone = Amsstone.all.each_with_index do |sto , d|
		    #end

		#if params[:category].blank?
			@amsgroup = Amsgroup.all.order("created_at DESC")
		#	@amsstone = Amsstone.all.order("created_at DESC")
		#	@amsfood = Amsfood.all.order("created_at DESC")
		#	@category = Category.all.order("created_at DESC")
		#else		
		#	@category_id = Category.find_by(categoryname: params[:category]).id
		#	@amsgroup = Amsgroup.where(category_id: @category_id).order("created_at DESC")
		#	@amsstone = Amsstone.where(category_id: @category_id).order("created_at DESC")
		#	@amsfood = Amsfood.where(category_id: @category_id).order("created_at DESC")
		#end

		if params[:stonecategory].blank?
			@amsstone = Amsstone.all.order("created_at DESC")
		else
			#@stonecategory_id = Stonecategory.find_by(categoryname: params[:stonecategory]).id
			@amsstone = Amsstone.where(stonecategory_id: @stonecategory_id).order("created_at DESC")

			#@resumes = Resume.where(soul_id: @soul).order("created_at DESC")
		end

		#if params[:category].blank?
		#	@amsgroup = Amsgroup.all.order("created_at DESC")
		#	@amsstone = Amsstone.all.order("created_at DESC")
		#	@amsfood = Amsfood.all.order("created_at DESC")
		#	@category = Category.all.order("created_at DESC")
		#else
		#	@category_id = Category.find_by(categoryname: params[:category]).id
		#	@amsgroup = Amsgroup.where(category_id: @category_id).order("created_at DESC")
		#	@amsstone = Amsstone.where(category_id: @category_id).order("created_at DESC")
		#	@amsfood = Amsfood.where(category_id: @category_id).order("created_at DESC")
		#end
#
#		if params[:foodcategory].blank?
#			@foodcategory = Foodcategory.all.order("created_at DESC")
#		else
#			@foodcategory_id = Foodcategory.find_by(categoryname: params[:foodcategory]).id
#			@foodcategory = Foodcategory.where(category_id: @category_id).order("created_at DESC")
#		end
#
#		if params[:groupcategory].blank?
#			@groupcategory = Groupcategory.all.order("created_at DESC")
#		else
#			@groupcategory_id = Groupcategory.find_by(categoryname: params[:groupcategory]).id
#			@groupcategory = Groupcategory.where(category_id: @category_id).order("created_at DESC")
#		end
	end

	def show
		
		
		@amsstony =  @amsstone.stonecategory_id
		@stonecategory = Stonecategory.where(stonecategory_id: @amsstony).order("created_at DESC")
		#@category_id = Category.find_by(name: params[:category]).id
		#@jobs = Job.where(category_id: @category_id).order("created_at DESC")
	end

	def new
		@amsstone = current_user.amsstones.build
	end

	def create
		@amsstone = current_user.amsstones.build(amsstone_params)

		if @amsstone.save
			redirect_to @amsstone, notice: "wish was succesfully updated!"
		else
			render 'new'
		end
	end

	def edit
		
	end

	def update
		if @amsstone.update(amsstone_params)
			redirect_to @amsstone
		else
			render "edit"
		end
	end

	def destroy
		@amsstone.destroy
		redirect_to @amsstone
	end

	private

	def amsstone_params
		params.require(:amsstone).permit(:titlerus, :number, :descriptionrus, :stonecategory_id, :imagestone, :amsstones_id)
	end

	def find_amsstone
		@amsstone = Amsstone.find(params[:id])
	end
	
end

app/helpers/amsstones_helper.rb
module AmsstonesHelper
end

app/views/amsstones/_stone_form.html.haml
.bodyams
  .col-xs-1.col-md-1
    .btn_back
    = link_to "Back", root_path, class: "btn btn-default"
  .col-xs-10.col-md-10
    .tit_desc_img_block
      %h1.colorgold  NEW STONE
      = simple_form_for @amsstone, html: { multipart: true } do |f|
        - if @amsstone.errors.any?
          #errors
            %p
              = @amsstone.errors.count
              Prevented this amsstone froms saving
            %ul
              - @amsstone.errors.full_messages.each do |msg|
                %li= msg
        .panel-body
          = f.collection_select :stonecategory_id, Stonecategory.all, :id, :categoryname, {promt: "Выберите Категорию", class: 'form-control'}
          = f.input :titlerus, label: 'resume Name', input_html: { title: "NAME of your resume", class: 'form-control'}
          
          = f.input :number, label: 'Link', input_html: { title: "NAME of your resume", class: 'form-control'}
          = f.input :descriptionrus, label: 'resume Name', input_html: { title: "NAME of your resume", class: 'form-control'}
          
          = f.input :imagestone, label: 'Attach an image that will be in this resume', input_html: { class: 'form-control'}

        .sub_button
          = f.button :submit, class: "btn btn-primary sub_button"
        .btn_bottom_back
          = link_to "Back", root_path, class: "btn btn-default btn_bottom_back"
  .col-xs-1.col-md-1

app/views/amsstones/edit.html.haml
%h1 Edit @amsstone.titlerus

= render "stone_form"

%br

app/views/amsstones/index.html.haml
%div.bodyams
  .bodyhead
    %div.amslogo
      = link_to image_tag( 'logo-ams.svg', :class => 'ams_logo_head' ), amsgroups_path, target: '_blank'
      %div.amslogolanguage
        %h3
          = link_to_unless_current "English",  amsgroups_path(locale: "en")
          \#{link_to_unless_current "Arabic",  amsgroups_path(locale: "ar")} |
          \#{link_to_unless_current "Rusian",  amsgroups_path(locale: "ru")}
    %div.tabbed
      %input{:type=>"radio", :name => "tabs", :id=>"tab-nav-1", :checked=> true}
        %label{:for=>"tab-nav-1"}=t 'welcome.ams'
      %input{:type=>"radio", :name => "tabs", :id=>"tab-nav-2"}
        %label{:for=>"tab-nav-2"}=t 'welcome.howwework'
      %input{:type=>"radio", :name => "tabs", :id=>"tab-nav-3"}
        %label{:for=>"tab-nav-3"}=t 'welcome.production'
      %input{:type=>"radio", :name => "tabs", :id=>"tab-nav-4"}
        %label{:for=>"tab-nav-4"}=t 'welcome.contacts'
      .bodyamsgroup
      %div{ :class => ['tabs']}

          
        %div.amsgroupproduction
          = render 'layouts/navigation'

          %div.stprod.amsproductsstones
            %h2=t 'welcome.stoneproduction' 
            .div.textcenter
              - Stonecategory.all.each do |cat|
                /= cat.categoryname
                %h3.inline

                  = link_to cat.categoryname , cat
                 
            .categoryblokstonefood
              - @amsstone.each do |s|
                .allproductplate.inline
                  %h4= link_to truncate(s.titlerus, length: 14), s
                  .allproductplateimg
                    = link_to s do
                      = image_tag s.imagestone.url(:thumb)  
                  - if user_signed_in?
                    %h5.stoneplatetext= link_to truncate(s.number, length: 20), s
                  - else
                    %h5.stoneplatetext #{truncate(s.number, length: 20)}
            
                /= link_to " #{truncate(s.descriptionrus, length: 7)}", pr.url, target: '_blank'
        /
          %div.stone_gallery
            - @amsgroup.each_slice(3) do |group|
              %div
                - group.each do  |s|
                  .ams_gallery_foto
                    = link_to s do
                      = image_tag s.imagegroup.url(:medium)
                  %h2= link_to s.titlerus, s
        %div
          %div.amsworktext

            %div.amsworknews.right
              %h1{:style => "color: #ffd700; text-align: center"} OUR NEWS
              - @amsgroup.each do |group|
                %h2
                  - if user_signed_in?
                    = link_to group.titlerus, group
                  - else
                    = group.titlerus
                  .newstime.right
                    %h5
                      = group.updated_at.day
                      ∕
                      = group.updated_at.month
                      ∕
                      = group.updated_at.year
                %h4{:style => "color: #ffd700;"}= group.descriptionrus
                %hr{:style => "border: 2px double #50156E; margin-top: 10px;"}
            %h1{:style => "color: #ffd700; text-align: center; margin-top: 0px;"}=t 'welcome.howweworktitle'
            %p=t 'welcome.howweworktext' 
          %div.amsgroupfoodandstone
            %div.amsgroupfoodandstoneplate.inline
              %div.amsgroupfshead.amsgroupfsheadgrey= link_to "AMS Stones", amsstones_path, class: " btn asmstone_button"
              %div.amsgroupfsbody
                %div.slides_fs
                  %ul
                    %li
                      = link_to image_tag( 'stone1', :class => 'amsgroupfoodfoto' ), amsstones_path
                    %li
                      = link_to image_tag( 'stone2', :class => 'amsgroupfoodfoto' ), amsstones_path
                    %li
                      = link_to image_tag( 'stone3', :class => 'amsgroupfoodfoto' ), amsstones_path
                    %li
                      = link_to image_tag( 'stone4', :class => 'amsgroupfoodfoto' ), amsstones_path
            %div.amsgroupfoodandstoneplate.inline
              %div.amsgroupfshead.amsgroupfsheadred= link_to "AMS Foods", amsfoods_path, class: " btn asmfood_button"
              %div.amsgroupfsbody
                %div.slides_fs
                  %ul
                    %li
                      = link_to image_tag( 'food1', :class => 'amsgroupfoodfoto' ), amsfoods_path
                    %li
                      = link_to image_tag( 'food2', :class => 'amsgroupfoodfoto' ), amsfoods_path
                    %li
                      = link_to image_tag( 'food3', :class => 'amsgroupfoodfoto' ), amsfoods_path
                    %li
                      = link_to image_tag( 'food4', :class => 'amsgroupfoodfoto' ), amsfoods_path
        %div 
          %div.amsworktext
            = render 'layouts/navigation'
        %div
          %div.amsmap.right
            %iframe{:allowfullscreen => "", :frameborder => "0", :height => "350", :src => "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2539.730208596946!2d30.431012037035497!3d50.46474843315227!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xdc777aaaf995bf05!2z0KTQu9C-0YDQsCDQn9Cw0YDQug!5e0!3m2!1sru!2sua!4v1479894063059", :style => "border:0", :width => "450"}
          
          .ams_contacts
            %h2=t 'welcome.contacts'
            %li.inline
              = link_to image_tag( 'mail.svg', :class => 'mail' ), amsgroups_path, target: '_blank'
              %div.number international.ams.group@gmail.com
            %li
              = link_to image_tag( 'skype.svg', :class => 'wel_contact' ), amsgroups_path, target: '_blank'
              = link_to image_tag( 'facebook-square.svg', :class => 'wel_contact' ), amsgroups_path, target: '_blank'
              
            %li
              = link_to image_tag( 'viber.svg', :class => 'wel_contact inline' ), amsgroups_path, target: '_blank'
              = link_to image_tag( 'whatsapp.svg', :class => 'wel_contact inline' ), amsgroups_path, target: '_blank'
              %div.number +380934637692     
            %li
              %h3=t 'welcome.adress'

app/views/amsstones/new.html.haml
%h1 NEW STONE FOTO

= render "stone_form"

%br

= link_to "Back", amsstones_path, class: "btn btn-default btn_bottom_back"

app/views/amsstones/show.html.haml
= render 'layouts/miniheader'
.headcurrentstone
  .div.headcurrentstoneams
    %h1.textcenter=t 'welcome.stoneproduction'
  .div.headcurrentstoneblocks.inline
    .div.headcurrentstonefirstblock.inline.left
      %h1= link_to @amsstone.stonecategory.categoryname, stonecategory_path(@amsstony)
      .div= image_tag @amsstone.imagestone.url(:simple), class: "headcurrentstonepicture"
    .div.headcurrentstonesecondblock.inline.left
      %h1
        = @amsstone.titlerus
      %h2
        = @amsstone.number
      %br
      %h3.textleft= @amsstone.descriptionrus
      %br


      - if user_signed_in?
        = link_to "Edit", edit_amsstone_path, class: "btn btn-default"
        = link_to "delete", amsstone_path, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default"
    .div.headcurrentstonethirdblock.inline
      %h1= link_to "All Stones", amsstones_path
.bodycurrentstone
  = image_tag @amsstone.imagestone.url(:hard, class: "ams_gallery_foto")