config/routes.rb
Rails.application.routes.draw do

  

  devise_for :users

  root 'amsgroups#welcome'
  
  scope "/:locale", locale: /en|ru|ar/ do
    
        end
      resources :amsgroups
      resources :amsgrouppictures
      resources :amsfoods
      resources :amsfoodpictures
      resources :amsstones
      resources :amsstonepictures

      resources :categories
      resources :foodcategories
      resources :stonecategories
      resources :groupcategories

  

end

app/models/amsfood.rb
class Amsfood < ActiveRecord::Base
  belongs_to :user
  belongs_to :foodcategory

  has_attached_file :imagefood, styles: { small: "116x116#" , medium: "252x302#", simple: "350x350#" , thumb: "150x150#", hard: "1152x1000#" }, default_url: "/images/:style/points.png"
  validates_attachment_content_type :imagefood, content_type: /\Aimage\/.*\z/	

  translates :titlerus, :descriptionrus
end

app/models/amsfoodpicture.rb
class Amsfoodpicture < ActiveRecord::Base

  belongs_to :user


  has_attached_file :imagefoodpicture, styles: { medium: "631x185#", thumb: "382x300#" }, default_url: "/images/:style/points.png"
  validates_attachment_content_type :imagefoodpicture, content_type: /\Aimage\/.*\z/

  translates :titlerus, :descriptionrus
end

app/models/amsgroup.rb
class Amsgroup < ActiveRecord::Base

  belongs_to :user
  belongs_to :groupcategory


	  has_attached_file :imagegroup, styles: { medium: "302x252#", thumb: "100x100#" }, default_url: "/images/:style/points.png"
  validates_attachment_content_type :imagegroup, content_type: /\Aimage\/.*\z/

  translates :titlerus, :descriptionrus
end

app/models/amsgrouppicture.rb
class Amsgrouppicture < ActiveRecord::Base


  belongs_to :user


  has_attached_file :imagegrouppicture, styles: { medium: "920x150#", thumb: "100x100#" }, default_url: "/images/:style/points.png"
  validates_attachment_content_type :imagegrouppicture, content_type: /\Aimage\/.*\z/

  translates :titlerus, :descriptionrus
end

app/models/amsstone.rb
class Amsstone < ActiveRecord::Base

  belongs_to :user
  belongs_to :stonecategory


  has_attached_file :imagestone, styles: { small: "116x116#" , medium: "252x302#", simple: "350x350#" , thumb: "150x150#", hard: "1152x1000#" }, default_url: "/images/:style/points.png"
  validates_attachment_content_type :imagestone, content_type: /\Aimage\/.*\z/

  translates :titlerus, :descriptionrus
end

app/models/amsstonepicture.rb
class Amsstonepicture < ActiveRecord::Base
	
  belongs_to :user


  has_attached_file :imagestonepicture, styles: { medium: "631x185#", thumb: "382x300#" }, default_url: "/images/points.png"
  validates_attachment_content_type :imagestonepicture, content_type: /\Aimage\/.*\z/


  translates :titlerus, :descriptionrus
end

app/models/category.rb
class Category < ActiveRecord::Base
	belongs_to :user

	#has_many :amsfoods
	#has_many :amsstones
	#has_many :amsgroups
end

app/models/foodcategory.rb
class Foodcategory < ActiveRecord::Base
		belongs_to :user

	has_many :amsfoods


	translates :categoryname
end

app/models/groupcategory.rb
class Groupcategory < ActiveRecord::Base
		belongs_to :user


	has_many :amsgroups

	translates :categoryname
end

app/models/stonecategory.rb
class Stonecategory < ActiveRecord::Base
		belongs_to :user


	has_many :amsstones

	translates :categoryname
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :amsfoods
  has_many :amsfoodpictures
  has_many :amsgroups
  has_many :amsgrouppictures
  has_many :amsstones
  has_many :amsstonepictures
  has_many :categories
  has_many :foodcategories
  has_many :groupcategories
  has_many :stonecategories
end

app/controllers/amsfoods_controller.rb
class AmsfoodsController < ApplicationController
	before_action :find_amsfood, only: [ :show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]


	def index
		#@amsgroup = Amsgroup.all.order("created_at DESC")
			@amsgrouppicture = Amsgrouppicture.all.order("created_at DESC")
		#@amsstone = Amsstone.all.order("created_at DESC")
			@amsstonepicture = Amsstonepicture.all.order("created_at DESC")
		#@amsfood = Amsfood.all.order("created_at DESC")
			@amsfoodpicture = Amsfoodpicture.all.order("created_at DESC")
		#@category = Category.all.order("created_at DESC")

			@amsgroup = Amsgroup.all.order("created_at DESC")


		#if params[:category].blank?
		#	@amsgroup = Amsgroup.all.order("created_at DESC")
		#	@amsstone = Amsstone.all.order("created_at DESC")
		#	@amsfood = Amsfood.all.order("created_at DESC")
		#	@category = Category.all.order("created_at DESC")
		#else
		#	@category_id = Category.find_by(categoryname: params[:category]).id
		#	@amsgroup = Amsgroup.where(category_id: @category_id).order("created_at DESC")
		#	@amsstone = Amsstone.where(category_id: @category_id).order("created_at DESC")
		#	@amsfood = Amsfood.where(category_id: @category_id).order("created_at DESC")
		#end

		if params[:foodcategory].blank?
			@amsfood = Amsfood.all.order("created_at DESC")
		else
			#@stonecategory_id = Stonecategory.find_by(categoryname: params[:stonecategory]).id
			@amsfood = Amsfood.where(foodcategory_id: @foodcategory_id).order("created_at DESC")

			#@resumes = Resume.where(soul_id: @soul).order("created_at DESC")
		end

		
	end

	def show
		@amsfoody =  @amsfood.foodcategory_id
		@foodcategory = Foodcategory.where(foodcategory_id: @amsfoody).order("created_at DESC")
	end

	def new
		@amsfood = current_user.amsfoods.build
	end

	def create
		@amsfood = current_user.amsfoods.build(amsfood_params)

		if @amsfood.save
			redirect_to @amsfood, notice: "wish was succesfully updated!"
		else
			render 'new'
		end
	end

	def edit
		
	end

	def update
		if @amsfood.update(amsfood_params)
			redirect_to @amsfood
		else
			render "edit"
		end
	end

	def destroy
		@amsfood.destroy
		redirect_to @amsfood
	end

	private

	def amsfood_params
		params.require(:amsfood).permit(:titlerus, :descriptionrus, :foodcategory_id, :imagefood, :amsfoods_id)
	end

	def find_amsfood
		@amsfood = Amsfood.find(params[:id])
	end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :find_category, only: [ :show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@category = Category.all.order("created_at DESC")
	end

	def show
		
	end

	def new
		@category = current_user.categories.build
	end

	def create
		@category = current_user.categories.build(category_params)

		if @category.save
			redirect_to @category, notice: "wish was succesfully updated!"
		else
			render 'new'
		end
	end

	def edit
		
	end

	def update
		if @category.update(category_params)
			redirect_to @category
		else
			render "edit"
		end
	end

	def destroy
		@category.destroy
		redirect_to @category
	end

	private

	def category_params
		params.require(:category).permit(:categoryname)
	end

	def find_category
		@category = Category.find(params[:id])
	end
	
end

app/helpers/amsfoodpictures_helper.rb
module AmsfoodpicturesHelper
end

app/helpers/amsfoods_helper.rb
module AmsfoodsHelper
end

app/helpers/amsgrouppictures_helper.rb
module AmsgrouppicturesHelper
end

app/helpers/amsgroups_helper.rb
module AmsgroupsHelper
end

app/helpers/amsstones_helper.rb
module AmsstonesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/foodcategories_helper.rb
module FoodcategoriesHelper
end

app/helpers/groupcategories_helper.rb
module GroupcategoriesHelper
end

app/helpers/stonecategories_helper.rb
module StonecategoriesHelper
end

app/views/categories/_category_form.html.haml
.bodyams
  .col-xs-1.col-md-1
    .btn_back
    = link_to "Back", root_path, class: "btn btn-default"
  .col-xs-10.col-md-10
    .tit_desc_img_block
      %h1.colorgold  NEW STONE
      = simple_form_for @category, html: { multipart: true } do |f|
        - if @category.errors.any?
          #errors
            %p
              = @category.errors.count
              Prevented this category froms saving
            %ul
              - @category.errors.full_messages.each do |msg|
                %li= msg
        .panel-body
          = f.input :categoryname, label: 'Имя Категории', input_html: { title: "ИМЯ КАТЕГОРИИ", class: 'form-control'}
          
        .sub_button
          = f.button :submit, class: "btn btn-primary sub_button"
        .btn_bottom_back
          = link_to "Back", root_path, class: "btn btn-default btn_bottom_back"
  .col-xs-1.col-md-1

app/views/categories/edit.html.haml
%h1 Edit @amsstone.titlerus

= render "category_form"

%br

app/views/categories/index.html.haml
%div.stoneheadmain
  %div.formargin
    %div.stonehead
      %div.stonelanguage.inline
        %ul
          %li.language EN
          %li.language AR
          %li.language RU 
      %div.stonelogo.inline
        .bootstile
          .col-xs-5.col-md-5
            
          .col-xs-7.col-md-7
            %div.slides.inline
              %ul
                %li
                  =image_tag( '1.jpg', :class => 'foto_slider_group' )
                  %div 
                    %p МРАМОРНЫЕ ИЗДЕЛИ
                %li
                  =image_tag( '2.jpg', :class => 'foto_slider_group' )
                  %div 
                    %p ПЛИТКА ИЗ МРАМОРА
                %li
                  =image_tag( '8.jpg', :class => 'foto_slider_group' )
                  %div 
                    %p МРАМОР ТЁМНЫЙ
                %li
                  =image_tag( '4.jpg', :class => 'foto_slider_group' )
                  %div 
                    %p МРАМОР БЕЛЫЙ
                %li
                  =image_tag( '6.jpg', :class => 'foto_slider_group' )
                  %div 
                    %p МРАМОР МРАМОРНЫЙ
                %li
                  =image_tag( '1.jpg', :class => 'foto_slider_group' )
                  %div 
                    %p МРАМОРИЩЕ
      %div.stonecontact.inline
        %li.contact 
          = link_to image_tag( 'skype.png', :class => 'contacts_to_stone' ), amsgroups_path, target: '_blank'
        %li.contact
          = link_to image_tag( 'github.png', :class => 'contacts_to_stone' ), amsgroups_path, target: '_blank'
        %li.contact
          = link_to image_tag( 'fb.png', :class => 'contacts_to_stone' ), amsgroups_path, target: '_blank'

.tabbedstones
  %input{:type=>"radio", :name => "sttabs", :id=>"stonestab-nav-1", :checked=> true}
    %label{:for=>"stonestab-nav-1"} AMS Group 
  %input{:type=>"radio", :name => "sttabs", :id=>"stonestab-nav-2"}
    %label{:for=>"stonestab-nav-2"} AMS How we work
  %input{:type=>"radio", :name => "sttabs", :id=>"stonestab-nav-3"}
    %label{:for=>"stonestab-nav-3"} Production 
  %input{:type=>"radio", :name => "sttabs", :id=>"stonestab-nav-4"}
    %label{:for=>"stonestab-nav-4"} контакты
  %div{ :class => ['stonestabs']}
    %div
      %div.amsgroup_maintext






    %div
      %h2 главная
      %p Компания <strong>AMS Internatioanl</strong> предоставляет услуги доставки\заказа материала и изделий из гранита, а так же предоставляет отдельные услуги грузодоставки подобных материалов между объектами, по Украине и странам Евросоюза. Более детальную информацию о материалах, их цене и контакты Вы можете найти в соответствующих разделах сайта.
    %div
      %h2 главная
      %p Компания <strong>AMS Internatioanl</strong> предоставляет услуги доставки\заказа материала и изделий из гранита, а так же предоставляет отдельные услуги грузодоставки подобных материалов между объектами, по Украине и странам Евросоюза. Более детальную информацию о материалах, их цене и контакты Вы можете найти в соответствующих разделах сайта.

      

    %div
      %h2 главная
      %p Компания <strong>AMS Internatioanl</strong> предоставляет услуги доставки\заказа материала и изделий из гранита, а так же предоставляет отдельные услуги грузодоставки подобных материалов между объектами, по Украине и странам Евросоюза. Более детальную информацию о материалах, их цене и контакты Вы можете найти в соответствующих разделах сайта.
      %div.stone_gallery
        - @category.each_slice(3) do |cat|
          %div
            - cat.each do  |c|
              .ams_gallery_foto
                %h2= link_to c.categoryname, c

app/views/categories/new.html.haml
%h1 NEW STONE FOTO

= render "category_form"

%br

= link_to "Back", categories_path, class: "btn btn-default btn_bottom_back"

app/views/categories/show.html.haml
.bodyams
  %h1 ЭТО КАТЕГОРИЯ
  %h2= @category.categoryname
  %br
  
  = link_to "Back", amsstones_path, class: "btn btn-default"
  - if user_signed_in?
    = link_to "Edit", edit_amsstone_path, class: "btn btn-default"
    = link_to "delete", amsstone_path, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default"