config/routes.rb
Rails.application.routes.draw do

  

  devise_for :users

  root 'amsgroups#welcome'
  
  scope "/:locale", locale: /en|ru|ar/ do
    
        end
      resources :amsgroups
      resources :amsgrouppictures
      resources :amsfoods
      resources :amsfoodpictures
      resources :amsstones
      resources :amsstonepictures

      resources :categories
      resources :foodcategories
      resources :stonecategories
      resources :groupcategories

  

end

app/models/amsfood.rb
class Amsfood < ActiveRecord::Base
  belongs_to :user
  belongs_to :foodcategory

  has_attached_file :imagefood, styles: { small: "116x116#" , medium: "252x302#", simple: "350x350#" , thumb: "150x150#", hard: "1152x1000#" }, default_url: "/images/:style/points.png"
  validates_attachment_content_type :imagefood, content_type: /\Aimage\/.*\z/	

  translates :titlerus, :descriptionrus
end

app/models/amsfoodpicture.rb
class Amsfoodpicture < ActiveRecord::Base

  belongs_to :user


  has_attached_file :imagefoodpicture, styles: { medium: "631x185#", thumb: "382x300#" }, default_url: "/images/:style/points.png"
  validates_attachment_content_type :imagefoodpicture, content_type: /\Aimage\/.*\z/

  translates :titlerus, :descriptionrus
end

app/models/amsgroup.rb
class Amsgroup < ActiveRecord::Base

  belongs_to :user
  belongs_to :groupcategory


	  has_attached_file :imagegroup, styles: { medium: "302x252#", thumb: "100x100#" }, default_url: "/images/:style/points.png"
  validates_attachment_content_type :imagegroup, content_type: /\Aimage\/.*\z/

  translates :titlerus, :descriptionrus
end

app/models/amsgrouppicture.rb
class Amsgrouppicture < ActiveRecord::Base


  belongs_to :user


  has_attached_file :imagegrouppicture, styles: { medium: "920x150#", thumb: "100x100#" }, default_url: "/images/:style/points.png"
  validates_attachment_content_type :imagegrouppicture, content_type: /\Aimage\/.*\z/

  translates :titlerus, :descriptionrus
end

app/models/amsstone.rb
class Amsstone < ActiveRecord::Base

  belongs_to :user
  belongs_to :stonecategory


  has_attached_file :imagestone, styles: { small: "116x116#" , medium: "252x302#", simple: "350x350#" , thumb: "150x150#", hard: "1152x1000#" }, default_url: "/images/:style/points.png"
  validates_attachment_content_type :imagestone, content_type: /\Aimage\/.*\z/

  translates :titlerus, :descriptionrus
end

app/models/amsstonepicture.rb
class Amsstonepicture < ActiveRecord::Base
	
  belongs_to :user


  has_attached_file :imagestonepicture, styles: { medium: "631x185#", thumb: "382x300#" }, default_url: "/images/points.png"
  validates_attachment_content_type :imagestonepicture, content_type: /\Aimage\/.*\z/


  translates :titlerus, :descriptionrus
end

app/models/category.rb
class Category < ActiveRecord::Base
	belongs_to :user

	#has_many :amsfoods
	#has_many :amsstones
	#has_many :amsgroups
end

app/models/foodcategory.rb
class Foodcategory < ActiveRecord::Base
		belongs_to :user

	has_many :amsfoods


	translates :categoryname
end

app/models/groupcategory.rb
class Groupcategory < ActiveRecord::Base
		belongs_to :user


	has_many :amsgroups

	translates :categoryname
end

app/models/stonecategory.rb
class Stonecategory < ActiveRecord::Base
		belongs_to :user


	has_many :amsstones

	translates :categoryname
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :amsfoods
  has_many :amsfoodpictures
  has_many :amsgroups
  has_many :amsgrouppictures
  has_many :amsstones
  has_many :amsstonepictures
  has_many :categories
  has_many :foodcategories
  has_many :groupcategories
  has_many :stonecategories
end

app/helpers/amsfoodpictures_helper.rb
module AmsfoodpicturesHelper
end

app/helpers/amsfoods_helper.rb
module AmsfoodsHelper
end

app/helpers/amsgroups_helper.rb
module AmsgroupsHelper
end

app/helpers/amsstones_helper.rb
module AmsstonesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/foodcategories_helper.rb
module FoodcategoriesHelper
end

app/helpers/groupcategories_helper.rb
module GroupcategoriesHelper
end

app/helpers/stonecategories_helper.rb
module StonecategoriesHelper
end

app/views/layouts/_miniheader.html.haml
.miniheader
  %div.miniheadlogo.inline.left
    = link_to image_tag( 'logo-ams.svg', :class => 'amslogominihead' ), amsgroups_path, target: '_blank'
  %div.miniheadcontacts.inline
    %h3
      %li.left
        = link_to image_tag( 'viber.svg', :class => 'wel_contact' ), amsgroups_path, target: '_blank'
        = link_to image_tag( 'whatsapp.svg', :class => 'wel_contact' ), amsgroups_path, target: '_blank'
        +380934637692
      %li.left
        = link_to image_tag( 'facebook-square.svg', :class => 'wel_contact' ), "https://www.facebook.com/AMS-International-Group-1180463538715714/?ref=page_internal", target: '_blank'
        = link_to image_tag( 'skype.svg', :class => 'wel_contact' ), "#", title: "Skype", data: { confirm: "Skype name is: international.ams.group ", :style => ' font-size: 30px;' }
        = link_to image_tag( 'mail.svg', :class => 'mail' ), "#", title: "Gmail", data: { confirm: "Mail adress is: international.ams.group@gmail.com", :style => ' font-size: 30px;' }
        international.ams.group@gmail.com
  %div.miniheadnation.inline.right
    %li.miniheadlanguage
      =link_to_unless_current "EN", locale: "en"
    %li.miniheadlanguage 
      =link_to_unless_current "RU", locale: "ru"
    %li.miniheadlanguage 
      =link_to_unless_current "AR", locale: "ar"

app/views/layouts/_navigation.html.haml
.dropdown.navprogdrop.inline
  %button#dropdownMenu1.btn.btn-default.dropdown-toggle#navbuttton{ :"aria-expanded" => "", :"aria-haspopup" => "true", :"data-toggle" => "dropdown", :type => "button" }
    =t 'welcome.navigateproduction'
    %span.caret
  %ul.navprogdropmenu.dropdown-menu{ :"aria-labelledby" => "dropdownMenu1", :style => "background-color: #ffd700;"}
    %div.navprogstone.stonecolor
      = link_to amsstones_path do
        %h2=t 'welcome.stoneproduction'
      - Stonecategory.all.each do |cat|
        .navprogfoodbloks
          %h3
            = link_to cat.categoryname , cat
            #{":"}

          - cat.amsstones.each do |s|
            %h4= link_to truncate(s.titlerus, length: 25), cat 
    %div.navprogfood.foodcolor 
      = link_to amsfoods_path do
        %h2=t 'welcome.foodproduction' 
      - Foodcategory.all.each do |food|
        .navprogfoodbloks         
          %h3
            = link_to food.categoryname , food
            #{":"}

          - food.amsfoods.each do |s|
            %h4= link_to truncate(s.titlerus, length: 25), food 

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title AMS
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

%body
  /
    %div.nation
    %ul
      %li.language
        =link_to_unless_current "EN", locale: "en"
      %li.language 
        =link_to_unless_current "RU", locale: "ru"
      %li.language 
        =link_to_unless_current "AR", locale: "ar"
    
    %h3
      = link_to_unless_current "English", root_path(locale: "en") | 
      |
      \#{link_to_unless_current "Rusian", root_path(locale: "ru")} |
      |
      \#{link_to_unless_current "Arabic", root_path(locale: "ar")}
  - if user_signed_in?
    %nav.navbar.navbar-default
      .conteiner
        .navbar-brand= link_to "Административная панель", root_path
        %ul.nav.navbar-nav
          %li= link_to "Создать Фото AMS", new_amsgrouppicture_path, class: "btn btn-default" 
          %li= link_to "Создать Новость AMS", new_amsgroup_path, class: "btn btn-default"
          %li= link_to "Создать Фото AMS Stone", new_amsstonepicture_path, class: "btn btn-default"
          %li= link_to "Создать Товар AMS Stone", new_amsstone_path, class: "btn btn-default"
          %li= link_to "Создать Фото AMS Food", new_amsfoodpicture_path, class: "btn btn-default"
          %li= link_to "Создать Товар AMS Food", new_amsfood_path, class: "btn btn-default"
          %li= link_to "Создать Категорию Stone", new_stonecategory_path, class: "btn btn-default"
          %li= link_to "Создать Категорию Food", new_foodcategory_path, class: "btn btn-default"
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Выйти", destroy_user_session_path, method: :delete
  - else
    %div.sign
      = link_to "Enter", new_user_session_path



  = yield
  .msg
    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert"